
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template
mp.jwt.verify.issuer=airhacks
mp.jwt.verify.publickey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmQNGe7hodUIkXOui4Th9TBPZS8N4Ng9OprRYBMet+9SZYNcYhl6I73NOv8rbeBc4fyLBVuQU8t87MaD4ToTbFJO1/ezaoQeGNkcyF+1zUCfNxmq4TLsYW5JHCFrWgMxjJGvqovD0HwJovu4aXt9o8GYTf4g3wWKuLyFCnj+4/n1sffthuykxeBTVmwww1SfhoURlWK189XoiqqkPGmjDi7h3Fs2IGmCzzkum8gnfDdntgVYcOgYpdlZZpvV6nefZzKr4iMavNqUWdXmsPlJGeNQRAGZHNAAHvcE6z7CLbphcUSeiBR32XWkhvngph3KJ57wzNg5WGaU9Ju44CDo+8QIDAQAB


