#!/bin/sh
mvn clean package
docker build -t dhruvishabhaliya/MSAResource .
docker rm -f MSAResource 2>/dev/null || true
docker run -it --name MSAResource -p 8080:8080 --name MSAResource dhruvishabhaliya/MSAResource
