#!/bin/sh
mvn clean package
docker build -t dhruvishabhaliya/EmpClient .
docker rm -f EmpClient 2>/dev/null || true
docker run -it --name EmpClient -p 8080:8080 --name EmpClient dhruvishabhaliya/EmpClient
