
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template
mp.jwt.verify.issuer=airhacks
mp.jwt.verify.publickey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwME/NyR8ZAn/vwYD+gRXMzCN2HZJG1ilwlK26/cHjS1urPc/mPgVxA7kqEJr/Dmvng/iKxd6sDSKypIu7mxJDE/B+ryCB5XeDfl4cDNVsVSzz0+V+uKptcYM7RCAsvOs1UkiwWVKSujmlGlgemc0dblbW5HuwHhP6yJYhfw+xr2TA6H8Up4elxiY1z8K+z7j8oy7I6tT9qy6UK5P0fydPNQdJ+9UFYDhpY4TB8Xx5D0CCqzBb1FIU203zFECWqZHmayfmv8cxmbqwVaAJbg4zG1ZStJJqv4ZbYjSo6kNbo0SSGb0SZNoHkxkXDe9i1ki5htweD9weGhGXuRyZ/MzyQIDAQAB

