
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template
mp.jwt.verify.publickey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvKASI+CZmGQlkq2RSk0Lg5j6KXg6s9fkWf8C5a4Gx3uz7++eHdhg7sJGsmDsTVwp1+qa1Wfu4p9jhP/XMSjcS0hCRScVHHr0ee3/xHqrUgSuHubmhQIrmJZI0m9UaAAjdE13ROptxAevZ7CgQio4AHxwh4FQa0hy1/L4v7HwATlZy3FSX5Xs0l5BFstm4pxRLzNhqPcJmzmuVrTvRucNtj+SpjOdDSJIqxFUcU+EgyyeWclCMPxucPp8x3cNKtig8WW6b8qIS+sUkgHcWSZs43yBkhhajwEmYlUumHbhxwuUlTjmvWUNoP+t+EcD8oOxcfzzh7urypcT3hI924AARQIDAQAB
mp.jwt.verify.issuer=airhacks

