
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

mp.jwt.verify.publickey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAngUMVizEPu2WN/7US4QNLzAy2EYlXJGwot9jWl+lF2JDblxahBLmYSqYYxTg6K7q1+wd2JnCSNfY3f7nfeKxFqmE/m3ZyaqMlvFHS5IXEu+quCQVaN9Eyb/S77kSSxNoiNVsm2/bffg0wszaTyLnkb4hI/jgB2wjENaP8gPbTf+PuNKWnQN+wgAT7o52F+o6G9qLM0/mmo9s3/HSsDAXp3MzAKUeOa5AU6ZVuz3mAnIjZzMLIijtgoYETDkRE+tlgP4Opxou9hhLF6WDLk20HiL+2Z0a8FK+yfrJDqaXZDeEPeC6He+sQZQMy0WXGH9AwxtyOCglwHZKmS7ADHFO3wIDAQAB
mp.jwt.verify.issuer=airhacks
