#!/bin/sh
mvn clean package
docker build -t dhruvishabhaliya/UserApplication .
docker rm -f UserApplication 2>/dev/null || true
docker run -it --name UserApplication -p 8080:8080 --name UserApplication dhruvishabhaliya/UserApplication
